# Generated by Django 5.2.8 on 2025-11-08 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Enter a unique course code (e.g., CS101).', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Enter the course title.', max_length=150)),
                ('credit_hours', models.DecimalField(decimal_places=1, help_text='Enter the credit hours for the course (e.g., 3.0).', max_digits=3)),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], help_text='Select the semester for this course.')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the department (e.g., Computer Science).', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Enter a unique short code for the department (e.g., CS).', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description about the department.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the designation/title of the staff (e.g., Lecturer, Professor, Lab Assistant).', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment')], help_text='Select the type of exam.', max_length=20)),
                ('date', models.DateField(help_text='Enter the date of the exam.')),
                ('total_marks', models.PositiveIntegerField(default=100, help_text='Enter the total marks of the exam.')),
                ('course', models.ForeignKey(help_text='Select the course for the exam.', on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_number', models.PositiveIntegerField(help_text='Enter a unique number for ordering the programs.', unique=True)),
                ('name', models.CharField(choices=[('BS Computer Science', 'BS Computer Science'), ('BS Information Technology', 'BS Information Technology'), ('BS Software Engineering', 'BS Software Engineering'), ('BS Artificial Intelligence', 'BS Artificial Intelligence'), ('BS Data Science', 'BS Data Science'), ('BS Cyber Security', 'BS Cyber Security'), ('BS Electrical Engineering', 'BS Electrical Engineering'), ('BS Mechanical Engineering', 'BS Mechanical Engineering'), ('MS Computer Science', 'MS Computer Science'), ('MS Data Science', 'MS Data Science'), ('MS Artificial Intelligence', 'MS Artificial Intelligence'), ('PhD Computer Science', 'PhD Computer Science'), ('PhD Information Technology', 'PhD Information Technology'), ('Diploma in Networking', 'Diploma in Networking'), ('Diploma in Web Development', 'Diploma in Web Development')], help_text='Select the program name from predefined choices.', max_length=100)),
                ('code', models.CharField(choices=[('BSCS-4321', 'BSCS-4321'), ('BSIT-4322', 'BSIT-4322'), ('BSSW-4323', 'BSSW-4323'), ('BSAI-4324', 'BSAI-4324'), ('BSDATA-4325', 'BSDATA-4325'), ('BSCYBER-4326', 'BSCYBER-4326'), ('BSEE-4327', 'BSEE-4327'), ('BSME-4328', 'BSME-4328'), ('MSCS-5321', 'MSCS-5321'), ('MSDATA-5322', 'MSDATA-5322'), ('MSAI-5323', 'MSAI-5323'), ('PHDCS-6321', 'PHDCS-6321'), ('PHDIT-6322', 'PHDIT-6322'), ('DNET-7321', 'DNET-7321'), ('DWEB-7322', 'DWEB-7322')], help_text='Select the program code from predefined choices (e.g., BSCS-4321).', max_length=20, unique=True)),
                ('program_type', models.CharField(choices=[('BS', 'Bachelor'), ('MS', 'Master'), ('PhD', 'Doctorate'), ('Diploma', 'Diploma')], help_text='Select the degree type for this program.', max_length=20)),
                ('duration_years', models.PositiveIntegerField(default=4, help_text='Enter the duration of the program in years.')),
                ('description', models.TextField(blank=True, help_text='Optional description about the program.', null=True)),
                ('department', models.ForeignKey(help_text='Select the department this program belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='app.department')),
            ],
            options={
                'ordering': ['program_number'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(help_text='Select the program this course belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.program'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter the full name of the staff member.', max_length=150)),
                ('staff_type', models.CharField(choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], help_text='Select the staff type: Teaching or Non-Teaching.', max_length=20)),
                ('email', models.EmailField(help_text='Enter the email address of the staff member.', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Enter the contact number of the staff member.', max_length=15, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, help_text='Date when the staff member joined.')),
                ('photo', models.ImageField(blank=True, help_text='Optional staff photo.', null=True, upload_to='staff/photos/')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the staff member is currently active.')),
                ('department', models.ForeignKey(help_text='Select the department the staff belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('designation', models.ForeignKey(help_text='Select the designation of the staff member.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.designation')),
                ('user', models.OneToOneField(help_text='Associate this staff member with a Django User account.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, help_text='Select the Head of Department (HOD).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='app.staff'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(help_text='Enter the unique registration number of the student.', max_length=30, unique=True)),
                ('full_name', models.CharField(help_text='Enter the full name of the student.', max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Select the gender of the student.', max_length=10)),
                ('dob', models.DateField(help_text='Enter the date of birth of the student.')),
                ('email', models.EmailField(help_text='Enter the email address of the student.', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Enter the contact number of the student.', max_length=15, unique=True)),
                ('address', models.TextField(help_text='Enter the address of the student.')),
                ('enrollment_year', models.PositiveIntegerField(help_text='Enter the enrollment year of the student.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the student is currently active.')),
                ('photo', models.ImageField(blank=True, help_text='Optional student photo.', null=True, upload_to='students/photos/')),
                ('program', models.ForeignKey(help_text='Select the program the student is enrolled in.', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.program')),
                ('user', models.OneToOneField(help_text='Associate this student with a Django User account.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, help_text='Enter the marks obtained by the student.', max_digits=5)),
                ('exam', models.ForeignKey(help_text='Select the exam.', on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
                ('student', models.ForeignKey(help_text='Select the student.', on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the fee amount.', max_digits=10)),
                ('due_date', models.DateField(help_text='Enter the due date for the payment.')),
                ('is_paid', models.BooleanField(default=False, help_text='Indicates whether the fee has been paid.')),
                ('payment_date', models.DateField(blank=True, help_text='Date when the payment was made (if paid).', null=True)),
                ('student', models.ForeignKey(help_text='Select the student for this fee record.', on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(auto_now_add=True, help_text='Date of admission.')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Select the current status of the admission.', max_length=20)),
                ('program', models.ForeignKey(help_text='Select the program the student is admitted to.', on_delete=django.db.models.deletion.CASCADE, to='app.program')),
                ('student', models.OneToOneField(help_text='Select the student for admission.', on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(help_text='Enter the semester number for this enrollment.')),
                ('year', models.PositiveIntegerField(help_text='Enter the academic year for this enrollment.')),
                ('date_enrolled', models.DateField(auto_now_add=True, help_text='Date when the student was enrolled in the course.')),
                ('course', models.ForeignKey(help_text='Select the course for enrollment.', on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student', models.ForeignKey(help_text='Select the student to enroll in the course.', on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the attendance record.')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], help_text='Select the attendance status.', max_length=10)),
                ('course', models.ForeignKey(help_text='Select the course.', on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student', models.ForeignKey(help_text='Select the student.', on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'date')},
            },
        ),
    ]
