# Generated by Django 5.2.8 on 2025-11-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='auto_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
